@description('The prefix to use for testing VM resources')
param deploymentPrefix string = 'testvm'

@description('Location for all resources')
param location string = resourceGroup().location

@description('Admin username for the virtual machine')
param adminUsername string

@description('Admin password for the virtual machine')
@secure()
param adminPassword string = ''

@description('The size of the VM')
param vmSize string = 'Standard_D2s_v3'

@allowed([
  'Manual'
  'AutoGenerated'
])
@description('How the password should be handled')
param passwordHandling string = 'AutoGenerated'

@description('Time when VM should auto-shutdown (e.g., "1900" for 7:00 PM)')
param vmAutoShutdownTime string = '1900'

@description('Time zone for auto-shutdown schedule (e.g., "Pacific Standard Time")')
param vmTimeZone string = 'Pacific Standard Time'

@description('Whether auto-shutdown should be enabled')
param enableAutoShutdown bool = true

@description('Log Analytics workspace ID from main deployment')
param logAnalyticsWorkspaceId string

// Generate a password only if passwordHandling is AutoGenerated
var generatedPassword = passwordHandling == 'AutoGenerated' && empty(adminPassword) ? '${uniqueString(resourceGroup().id, deployment().name)}Aa1!' : ''
var actualAdminPassword = passwordHandling == 'AutoGenerated' && empty(adminPassword) ? generatedPassword : adminPassword

// Variables
var networkSecurityGroupName = '${deploymentPrefix}-nsg'
var virtualNetworkName = '${deploymentPrefix}-vnet'
var vmName = '${deploymentPrefix}-vm'
var managedIdentityName = '${deploymentPrefix}-managed-identity'
var keyVaultName = '${deploymentPrefix}-kv-${uniqueString(resourceGroup().id)}'

// Central managed identity for all services
resource centralManagedIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2018-11-30' = {
  name: managedIdentityName
  location: location
}

// Networking module
module networking '../../bicep/networking.bicep' = {
  name: 'testVmNetworkingDeployment'
  params: {
    virtualNetworkName: virtualNetworkName
    networkSecurityGroupName: networkSecurityGroupName
    location: location
  }
}

// Key Vault module for storing test VM secrets
module keyVault '../../bicep/key-vault.bicep' = {
  name: 'testVmKeyVaultDeployment'
  params: {
    keyVaultName: keyVaultName
    location: location
    adminUsername: adminUsername
    adminPassword: actualAdminPassword
    eventHubNamespaceName: 'none' // Not needed for test VMs
    managedIdentityPrincipalId: centralManagedIdentity.properties.principalId
    managedIdentityId: centralManagedIdentity.id
  }
}

// VM module
module vm './vm-windows.bicep' = {
  name: 'testVmDeployment'
  params: {
    vmName: vmName
    virtualNetworkName: networking.outputs.virtualNetworkName
    subnetId: networking.outputs.defaultSubnetId
    adminUsername: adminUsername
    adminPassword: actualAdminPassword
    vmSize: vmSize
    location: location
    workspaceId: logAnalyticsWorkspaceId
    managedIdentityId: centralManagedIdentity.id
    keyVaultName: keyVault.outputs.keyVaultName
  }
}

// Data Collection Rules
module dataCollection './data-collection.bicep' = {
  name: 'testVmDataCollectionDeployment'
  params: {
    location: location
    workspaceId: logAnalyticsWorkspaceId
    vmId: vm.outputs.vmId
    managedIdentityId: centralManagedIdentity.id
  }
  dependsOn: [
    vm
  ]
}

// VM Auto-Shutdown Schedule
resource autoShutdownSchedule 'Microsoft.DevTestLab/schedules@2018-09-15' = if(enableAutoShutdown) {
  name: 'shutdown-computevm-${vmName}'
  location: location
  properties: {
    status: 'Enabled'
    taskType: 'ComputeVmShutdownTask'
    dailyRecurrence: {
      time: vmAutoShutdownTime
    }
    timeZoneId: vmTimeZone
    notificationSettings: {
      status: 'Disabled'
    }
    targetResourceId: vm.outputs.vmId
  }
}

// Outputs
output vmName string = vm.outputs.vmName
output vmFqdn string = vm.outputs.vmFqdn
output vmId string = vm.outputs.vmId
output keyVaultName string = keyVault.outputs.keyVaultName
output vmManagedIdentityClientId string = vm.outputs.vmManagedIdentityClientId
